---
jobs:
  test:
    name: 'Solaris (${{ matrix.perl }})'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: test
        name: Test in Solaris
        uses: vmactions/solaris-vm@v1
        with:
          prepare: |
            pkgutil -y -i gcc5core gcc5g++ socat git curl tree
            git clone --depth 1 --branch v${{matrix.perl}} https://github.com/Perl/perl5.git
            cd perl5
            ./Configure -des -Dusethreads -Duseshrplib=false -Dnoextensions=ODBM_File -A
            make
            make install
            cd ..
          run: |
            pwd
            ls -lah
            /opt/bin/perl -V
            curl -L https://cpanmin.us | /opt/bin/perl - -v .
          sync: rsync
          usesh: true
    strategy:
      fail-fast: false
      matrix:
        perl:
          - 5.38.2
name: Solaris
on:
  pull_request:
    branches: '*'
  push:
    branches: '*'
