---
jobs:
  build:
    name: 'Perl ${{ matrix.perl }} on ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry
          install-modules-args: --with-configure --installdeps --notest -v .
          install-modules-with: cpanm
          multi-thread: true
          perl-version: '${{ matrix.perl }}'
      - run: cpanm -v .
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        perl:
          - 5.38
          - 5.36
on:
  pull_request: ~
  push: ~
  schedule:
    - cron: 42 5 * * 0
  workflow_dispatch: ~
